### ISSUE TITLE
AVX builds don't support arbitrary grids

### ISSUE THREAD

**Issue by szaman19** [ParticleGrid/ParticleGrid#15]
Currently, the AVX enabled-build, which is the default, only supports grid sizes divisible by 8. This is definitely not the ideal case and should be addressed ASAP. The error is also silent and generates corrupted grids with garbage memory values. 

- Simple fix is to disable AVX all together
- Dynamic dispatching depending on the grid size requested

**Comment by denfromufa** [comment]
@szaman19 can you simplify this fix with padding to sizes divisible by 8?

**Comment by szaman19** [comment]
@denfromufa Yup, realized later that that'd probably be the ideal solution. In effect we just need the innermost loop to have a stride of 8 (be divisible by 8). So padding needs to be only along a single dimension along the grid.
